name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
          run_install: |
            - args: [--no-frozen-lockfile]

      - name: Build packages
        shell: bash
        run: |
          pnpm -w build

      - name: Run tests
        shell: bash
        run: |
          pnpm -w test

      - name: Lint packages
        shell: bash
        run: |
          pnpm -w lint

      - name: Build packages
        shell: bash
        run: |
          pnpm -w build:docs

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'bot: prepare update changeset'
          title: 'bot: publish update'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
